In [1]:
import pandas as pd
import numpy as np
import keras

/home/dmlab/ksedm1/anaconda3/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# In this tutorial, we will use a store_C dataset.      # /data: 50,000 user dataset  /data_sample: 500 user sample dataset
pre_release_path = '../data/indoor/store_C/'

# Load dataset
train_labels = pd.read_csv(pre_release_path+'train_labels.tsv', sep='\t')
test_labels = pd.read_csv(pre_release_path+'test_labels.tsv', sep='\t')
train_visits = pd.read_csv(pre_release_path+'train_visits.tsv', sep='\t')
test_visits = pd.read_csv(pre_release_path+'test_visits.tsv', sep='\t')
wifi_sessions = pd.read_csv(pre_release_path+'wifi_sessions.tsv', sep='\t')

wifi_sessions = wifi_sessions.set_index('index')

In [3]:
wifi_sessions

wifi_id          ts           area  dwell_time
index                                                  
0          30332  1483200531            out         478
1          25302  1483223630            out          54
2          40733  1483224345            out          37
3          19000  1483224999            out          71
4          24203  1483225450            out          10
5          39054  1483225549            out          42
6           6987  1483226466            out          66
7          18558  1483226531            out          57
8          42095  1483226598            out        1287
9          42095  1483226627             in           8
10         42095  1483226627             1f           8
11         43944  1483226764            out          67
13         32626  1483227203            out          43
14         43134  1483227651            out          18
15         39054  1483227756            out          63
17         14518  1483227862            out          77
18         23190  1483228039            out          14
19         28797  1483228199            out           2
20          4371  1483228345            out           8
21          7604  1483228506            out         689
22          7604  1483228562             1f         430
23          7604  1483228562             in         430
24         30213  1483228577            out          92
25         30351  1483228577            out        3535
26         44996  1483228696            out         596
27         12818  1483228704            out          60
28         19141  1483228820            out          61
29         46866  1483229029            out          62
30         29135  1483229143            out          43
31         17404  1483229423            out          64
...          ...         ...            ...         ...
1761401    30195  1509711998            out        1330
1761402    34616  1509712010            out         169
1761403    34616  1509712011   2f-hair-care          72
1761404    34616  1509712013         2f-xtm         118
1761405    34616  1509712028    2f-favorite           4
1761406    34616  1509712031  2f-hairstudio         100
1761408    31577  1509712059         2f-xtm          96
1761409    31577  1509712071       2f-enter          22
1761410    34616  1509712080   2f-body-care          11
1761411    31577  1509712100    2f-favorite          49
1761412    31577  1509712103  2f-hairstudio          49
1761413    30195  1509712132   2f-hair-care         314
1761414    30195  1509712197    2f-favorite           4
1761416    25363  1509712235             in         955
1761417    25363  1509712235     2f-texfree         690
1761418    25363  1509712235             2f         955
1761419    25363  1509712239    new-2f-food         686
1761420    31577  1509712241     2f-texfree          24
1761422    25363  1509712253            out         860
1761425    25363  1509712308  2f-hairstudio         759
1761427    25363  1509712430         2f-xtm         666
1761428    30195  1509712455       2f-enter         392
1761429    30195  1509712471   2f-body-care         520
1761430    25363  1509712489    2f-favorite          79
1761432    25363  1509712730     2f-counter         393
1761433    25363  1509712736        2f-cafe         453
1761434    30195  1509713020         2f-xtm         157
1761435    30195  1509713074  2f-hairstudio          93
1761442    30195  1509713227    new-2f-food          23
1761443    30195  1509713233        2f-cafe         107

[1460336 rows x 4 columns]

In [65]:
test_unk_interval_time / 86400

0        203.481412
1         50.942951
2         76.537106
3        192.145069
4         33.219086
5        262.386898
6         41.209572
7        235.034572
8        203.008067
9        247.500718
10       244.154977
11       245.413519
12       149.810822
13       209.103924
14       182.016169
15       298.436806
16       206.930313
17       242.313218
18       274.319850
19       199.493079
20       269.036782
21       276.302361
22        71.097488
23       235.309549
24       243.049850
25        91.751042
26        57.172431
27       222.339838
28       247.449907
29        43.021204
            ...    
21258     15.234595
21259    150.785405
21260     33.092662
21261     98.312928
21262    224.108808
21263    255.297951
21264    212.518021
21265    272.276458
21266    214.317153
21267    259.511123
21268    154.770150
21269    225.434780
21270    264.495093
21271    278.389641
21272     76.779954
21273    280.449525
21274    215.423576
21275     78.036458
21276    102.917697


In [63]:
test_visits

visit_id  wifi_id   date  \
0       v70173        1  17370   
1       v70174        9  17364   
2       v70175       10  17358   
3       v70176       11  17359   
4       v70177       12  17364   
5       v70178       14  17429   
6       v70179       17  17369   
7       v70180       18  17402   
8       v70181       22  17370   
9       v70182       24  17414   
10      v70183       27  17411   
11      v70184       28  17412   
12      v70185       29  17381   
13      v70186       30  17376   
14      v70187       31  17349   
15      v70188       32  17465   
16      v70189       35  17431   
17      v70190       36  17409   
18      v70191       37  17441   
19      v70192       38  17366   
20      v70193       39  17436   
21      v70194       40  17443   
22      v70195       42  17400   
23      v70196       44  17402   
24      v70197       46  17410   
25      v70198       47  17407   
26      v70199       51  17357   
27      v70200       52  17389   
28      v70201       55  17414   
29      v70202       57  17356   
...        ...      ...    ...   
21258   v91431    49928  17351   
21259   v91432    49930  17420   
21260   v91433    49931  17375   
21261   v91434    49932  17438   
21262   v91435    49938  17391   
21263   v91436    49939  17422   
21264   v91437    49943  17379   
21265   v91438    49947  17439   
21266   v91439    49953  17381   
21267   v91440    49955  17426   
21268   v91441    49956  17420   
21269   v91442    49957  17392   
21270   v91443    49958  17431   
21271   v91444    49959  17445   
21272   v91445    49960  17359   
21273   v91446    49962  17447   
21274   v91447    49964  17382   
21275   v91448    49966  17362   
21276   v91449    49967  17393   
21277   v91450    49970  17351   
21278   v91451    49971  17439   
21279   v91452    49974  17419   
21280   v91453    49978  17443   
21281   v91454    49980  17434   
21282   v91455    49981  17383   
21283   v91456    49990  17442   
21284   v91457    49996  17382   
21285   v91458    49997  17381   
21286   v91459    49999  17349   
21287   v91460    50000  17414   

                                                 indices  \
0                                                1312466   
1      1283776;1283779;1283784;1283793;1283805;128381...   
2                                        1246366;1246375   
3                                        1252370;1252415   
4                        1283417;1283469;1283484;1283490   
5                                                1627663   
6                                1305530;1305543;1305583   
7                                1471123;1471151;1471152   
8      1308606;1308624;1308635;1308649;1308659;130867...   
9      1546634;1546650;1546731;1546734;1546814;154682...   
10                       1523318;1523319;1523325;1523340   
11                                               1532778   
12                                       1364932;1364935   
13     1337321;1337330;1337332;1337333;1337334;133734...   
14     1198835;1198836;1198866;1198894;1198895;119889...   
15     1753227;1753228;1753230;1753231;1753232;175323...   
16                       1638362;1638364;1638367;1638378   
17     1512664;1512694;1512809;1512868;1512914;151298...   
18     1691753;1691767;1691769;1691776;1691845;169188...   
19     1293014;1293015;1293078;1293196;1293273;129327...   
20     1668966;1668968;1668969;1668988;1669001;166900...   
21     1702779;1702792;1702797;1702829;1702833;170289...   
22                                       1460926;1460927   
23     1473136;1473147;1473263;1473264;1473265;147329...   
24     1516453;1516454;1516455;1516459;1516462;151646...   
25                       1501390;1501412;1501413;1501415   
26     1245301;1245303;1245325;1245328;1245331;124534...   
27                                               1401098   
28     1545673;1545819;1545823;1545824;1546165;154624...   
29     1239878;1239893;1239961;1239974;1239976;124009...   
...                                  

In [4]:
### Before feature engineering, querying some useful information from wifi-sessions data, and add to the dataframe.
import time
def add_infos(df):  
    df['l_index'] = df['indices'].apply(lambda x: [int(y) for y in x.split(';')])

    newidx = [item for sublist in list(df.l_index) for item in sublist]
    tmpdf = wifi_sessions.loc[newidx]
    traj_lens = df.l_index.apply(len)

    tmp_areas = list(tmpdf['area'])
    tmp_dt = list(tmpdf['dwell_time'])
    tmp_ts_start = list(np.array(tmpdf['ts']))
    tmp_ts_end = list(np.array(tmpdf['ts']) + np.array(tmp_dt))  # end time

    rslt_dt = []
    rslt_areas = []
    rslt_ts_start = []
    rslt_ts_end = []

    i = 0
    for x in traj_lens:
        rslt_dt.append(tmp_dt[i:i + x])
        rslt_areas.append(tmp_areas[i:i + x])
        rslt_ts_start.append(min(tmp_ts_start[i:i+x]))
        rslt_ts_end.append(max(tmp_ts_end[i:i+x]))
        i += x

    df['dwell_times'] = rslt_dt
    df['areas'] = rslt_areas
    df['ts_start'] = rslt_ts_start
    df['ts_end'] = rslt_ts_end
    return df

##### Very slow approach, so revised.    
#     df['dwell_times'] = df['l_index'].apply(lambda x: [wifi_sessions.loc[idx]['dwell_time'] for idx in x])
#     t2 = time.time()
#     print(t2-t1)
#     df['areas'] = df['l_index'].apply(lambda x: [wifi_sessions.loc[idx]['area'] for idx in x])
#     t3 = time.time()
#     print(t3-t2)
    return df

In [5]:
train_visits = add_infos(train_visits)
test_visits = add_infos(test_visits)

In [6]:
train_visits.dwell_times.head(3)

0                    [93, 55, 36, 2, 9, 11, 346, 2, 5]
1    [534, 29, 495, 483, 432, 365, 354, 339, 304, 2...
2    [897, 736, 979, 1979, 1629, 1761, 1757, 684, 8...
Name: dwell_times, dtype: object

In [12]:
assert all(train_visits.ts_end-train_visits.ts_start >= 0)

In [13]:
# 방문 횟수 

train_visits['tmp'] = 1
train_visits['nvisits'] = train_visits.groupby(['wifi_id'])['tmp'].cumsum()
wid_nvisit = train_visits.iloc[list(train_visits['wifi_id'].drop_duplicates(keep='last').index)][['wifi_id','nvisits']]
d_wid_nvisit = {}
for wid, nvisit in zip(wid_nvisit['wifi_id'], wid_nvisit['nvisits']):
    d_wid_nvisit[wid] = nvisit
test_visits['tmp'] = 1
test_visits['prev_vcount'] = test_visits['wifi_id'].apply(lambda x: d_wid_nvisit.get(x, 0))
test_visits['nvisits'] = test_visits.groupby(['wifi_id'])['tmp'].cumsum()+test_visits['prev_vcount']
del train_visits['tmp'], test_visits['tmp'], test_visits['prev_vcount'], wid_nvisit


In [49]:
# unk_revisit_interval

first_ts_start = min(train_visits['ts_start'])
c1 = train_visits.groupby(['wifi_id'])['ts_start']
c2 = train_visits.groupby(['wifi_id'])['ts_end']
train_prev_revisit_interval = (c1.shift(periods=0) - c2.shift(periods=1))
train_left_observation_time = train_visits['ts_start'] - np.full(len(train_visits), first_ts_start)
train_unk_revisit_interval = np.minimum(train_prev_revisit_interval.fillna(1e10), train_left_observation_time)

train_visits['tmp'] = 1
train_visits['nvisits'] = train_visits.groupby(['wifi_id'])['tmp'].cumsum()
wid_ts_end = train_visits.iloc[list(train_visits['wifi_id'].drop_duplicates(keep='last').index)][['wifi_id','ts_end']]
d_wid_ts_end = {}
for wid, ts_end in zip(wid_ts_end['wifi_id'], wid_ts_end['ts_end']):
    d_wid_ts_end[wid] = ts_end
    
test_left_appeared_time = test_visits['wifi_id'].apply(lambda x: d_wid_ts_end.get(x, first_ts_start))
test_unk_interval_time = test_visits['ts_start'] - test_left_appeared_time

In [82]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(copy=True)
scaler.fit_transform(train_visits[['nvisits']])

/home/dmlab/ksedm1/anaconda3/envs/py36/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


array([[0.        ],
       [0.        ],
       [0.02564103],
       ...,
       [0.        ],
       [0.        ],
       [0.        ]])

In [98]:
from sklearn import metrics
sklearn.metrics.mean_squared_error(train_labels['revisit_interval'], train_labels['revisit_interval'])

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [105]:
idcs = np.argwhere(~np.isnan(train_labels['revisit_interval']))
sklearn.metrics.mean_squared_error(y_true=np.array(train_labels['revisit_interval'])[idcs],
                                   y_pred=np.array(train_labels['revisit_interval'])[idcs])

0.0

In [53]:
test_unk_interval_time/86400

0        203.481412
1         50.942951
2         76.537106
3        192.145069
4         33.219086
5        262.386898
6         41.209572
7        235.034572
8        203.008067
9        247.500718
10       244.154977
11       245.413519
12       149.810822
13       209.103924
14       182.016169
15       298.436806
16       206.930313
17       242.313218
18       274.319850
19       199.493079
20       269.036782
21       276.302361
22        71.097488
23       235.309549
24       243.049850
25        91.751042
26        57.172431
27       222.339838
28       247.449907
29        43.021204
            ...    
21258     15.234595
21259    150.785405
21260     33.092662
21261     98.312928
21262    224.108808
21263    255.297951
21264    212.518021
21265    272.276458
21266    214.317153
21267    259.511123
21268    154.770150
21269    225.434780
21270    264.495093
21271    278.389641
21272     76.779954
21273    280.449525
21274    215.423576
21275     78.036458
21276    102.917697


In [46]:
test_left_appeared_time

0        1483231817
1                 1
2                 1
3        1483231817
4                 1
5        1483231817
6                 1
7        1483231817
8        1483231817
9        1483231817
10       1483231817
11       1483231817
12                1
13       1483231817
14       1483231817
15       1483231817
16                1
17       1483231817
18       1483231817
19       1483231817
20       1483231817
21       1483231817
22                1
23       1483231817
24       1483231817
25                1
26                1
27       1483231817
28       1483231817
29                1
            ...    
21258             1
21259             1
21260             1
21261             1
21262    1483231817
21263    1483231817
21264    1483231817
21265    1483231817
21266    1483231817
21267    1483231817
21268             1
21269    1483231817
21270    1483231817
21271    1483231817
21272             1
21273    1483231817
21274    1483231817
21275             1
21276             1


In [14]:
train_visits['ts_start']

visit_id  wifi_id   date  \
0           v0        2  17208   
1           v1        3  17169   
2           v2        3  17211   
3           v3        3  17218   
4           v4        3  17220   
5           v5        3  17232   
6           v6        3  17233   
7           v7        3  17269   
8           v8        3  17321   
9           v9        3  17332   
10         v10        3  17334   
11         v11        4  17202   
12         v12        5  17269   
13         v13        6  17227   
14         v14        7  17305   
15         v15        8  17201   
16         v16        8  17204   
17         v17        9  17182   
18         v18        9  17313   
19         v19       10  17281   
20         v20       12  17254   
21         v21       12  17289   
22         v22       12  17328   
23         v23       12  17331   
24         v24       13  17305   
25         v25       13  17306   
26         v26       15  17291   
27         v27       16  17286   
28         v28       17  17328   
29         v29       19  17172   
...        ...      ...    ...   
70143   v70143    49969  17284   
70144   v70144    49973  17267   
70145   v70145    49976  17248   
70146   v70146    49976  17331   
70147   v70147    49977  17273   
70148   v70148    49979  17274   
70149   v70149    49981  17203   
70150   v70150    49981  17296   
70151   v70151    49981  17299   
70152   v70152    49981  17331   
70153   v70153    49981  17345   
70154   v70154    49982  17316   
70155   v70155    49983  17174   
70156   v70156    49984  17181   
70157   v70157    49985  17204   
70158   v70158    49985  17205   
70159   v70159    49985  17206   
70160   v70160    49986  17200   
70161   v70161    49987  17259   
70162   v70162    49988  17343   
70163   v70163    49989  17274   
70164   v70164    49991  17224   
70165   v70165    49992  17182   
70166   v70166    49992  17183   
70167   v70167    49993  17290   
70168   v70168    49994  17254   
70169   v70169    49994  17293   
70170   v70170    49995  17316   
70171   v70171    49996  17227   
70172   v70172    49998  17239   

                                                 indices  \
0      312901;312922;312937;312957;312962;313032;3130...   
1      23563;23564;23575;23576;23587;23597;23600;2360...   
2      336183;336206;336210;336222;336241;336286;3362...   
3      399632;399635;399642;399681;399725;399812;3998...   
4      414621;414622;414623;414625;414629;417423;4174...   
5      534304;534326;534328;534348;534359;534418;5344...   
6       542927;542932;542941;543000;543032;543062;543096   
7      760611;760617;760621;760645;760662;760674;7606...   
8      1042353;1042356;1042357;1042358;1042359;104236...   
9      1107746;1107750;1107769;1107775;1107796;110779...   
10     1118894;1118899;1118900;1118910;1118946;111896...   
11                           261246;261306;261307;261376   
12                    763085;763094;763097;763131;763140   
13                           481574;481624;481692;481698   
14     949637;949639;949662;949675;949681;949689;9497...   
15             250989;250991;250994;251021;251030;251048   
16     273175;273224;273267;273268;273269;273290;2733...   
17     134075;134077;134082;134092;134093;134194;1341...   
18      995568;995571;995581;995583;995662;995690;995697   
19     830429;830431;830437;830441;830451;830472;8304...   
20     676813;676815;676816;676854;676872;676934;6769...   
21      870826;870830;870840;870904;870907;870931;870979   
22     1087575;1087586;1087588;1087599;1087613;108763...   
23     1102038;1102039;1102040;1102043;1102045;110204...   
24                                  951724;951786;951841   
25     955248;955252;955266;955271;955276;955312;9553...   
26     880491;880493;880500;880519;880520;880537;8805...   
27     851474;851494;851496;851497;851498;851500;8515...   
28     1083923;1083925;1083929;1083936;1083941;108394...   
29     48235;48237;48245;48265;48278;48282;48299;4843...   
...                                  

In [ ]:
### Sample code to generate features 

def statistical_feature_generator(x):
    fs = []

    total_dwell_time = sum(x['dwell_times'])   # total dwell time
    num_area_trajectory_have = len(x['dwell_times'])  # the number of area
    num_unique_area_sensed = len(set(x['areas']))  # the number of unique areas
    
    fs.append(total_dwell_time)
    fs.append(num_area_trajectory_have)  
    fs.append(num_unique_area_sensed)     
    
    return fs


def add_statistical_features(train_visits):
    df = train_visits.copy()
    
    features = df.apply(lambda x: statistical_feature_generator(x), axis=1)
    featureName = ['total_dwell_time', 'num_area', 'num_unique_area']
    
    fdf = pd.DataFrame(list(np.asarray(features)), index=features.index, columns = featureName)
    
    # Combine feature values to the dataframe
    df = pd.concat([df, fdf], axis=1)
    del fdf
    
    return df

In [ ]:
train_visits = add_statistical_features(train_visits)
test_visits = add_statistical_features(test_visits)

In [ ]:
train_visits['date_rel'] = train_visits['date']-min(train_visits.date)
test_visits['date_rel'] = test_visits['date']-min(train_visits.date)

In [ ]:
train_visits.head(3)

In [ ]:
col_names = train_visits.columns

In [ ]:
train_visits.iloc[0]

In [ ]:
train_visits.iloc[0]

In [ ]:
train_visits['dwell_times']=train_visits['dwell_times'].apply(lambda x: x[:3])

In [ ]:
col_names.index('ts_end')+1

In [ ]:
def gener():
    def __gen__():
        for idx in train_visits.index[:120]:
            visit = train_visits.iloc[idx]
            label = train_labels.iloc[idx]
            yield visit['visit_id'], visit['dwell_times'], [visit[col] for col in col_names[-4:]], label['revisit_intention']

    gen = __gen__()
    while True:
        batch = [np.stack(x) for x in zip(*(next(gen) for _ in range(20)))]
        yield [batch[0].reshape(-1, 1)]+[batch[i] for i in range(1,3)], keras.utils.to_categorical(batch[-1],2)


In [ ]:
next(gener())

In [ ]:
train_visits

In [ ]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]

for i,j in zip(a,b):
    print(i+j)

In [ ]:
test = [[1,2,3],[4,5,6]]
cstest = tf.cumsum(test, exclusive = True, axis = 1)
print(cstest)

In [ ]:
import code

code.interact(local=locals())

In [ ]:
import tensorflow as tf

In [ ]:
tf_x = tf.placeholder(tf.int32, [128, 13], name="tf_x")
embeddings = tf.Variable(tf.random_normal([1580000, 32], stddev=0.1))
x_emds = tf.nn.embedding_lookup(embeddings, tf_x) #이게 128 X 13 X 32 행렬됨
input = tf.reshape(x_emds, [128, 13 * 32])

In [ ]:
print (x_emds)

In [ ]:
import tensorflow as tf
a = tf.truncated_normal([16, 1], dtype=tf.float64)

In [ ]:
X = [tf.sparse_placeholder(tf.float64) for i in range(0, 16)]
X[0]

In [ ]:
w0 = []
w0.append(tf.Variable(tf.truncated_normal([5, 1], dtype=tf.float64)))
w0.append(tf.Variable(tf.truncated_normal([22, 20], dtype=tf.float64)))

In [ ]:
dense_input = tf.concat([tf.sparse_tensor_dense_matmul(X[i], w0[i]) for i in range(2)], 1)

In [ ]:
[tf.sparse_tensor_dense_matmul(X[i], w0[i]) for i in range(2)]

In [17]:
import numpy as np
import pandas as pd
import keras.backend as K

/home/dmlab/ksedm1/anaconda3/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [12]:
def custom_loss_numpy(encodings, user_id):
    # user_id: a pandas series of users
    # encodings: a pandas dataframe of encodings
    
    batch_dist = 0
    
    for i in range(len(user_id)):
        first_row = encodings.iloc[i,:].values
        first_user = user_id[i]
        
        for j in range(i+1, len(user_id)):
            second_row = encodings.iloc[j,:].values
            second_user = user_id[j]
            
        # Compute distance: if the users are same then Euclidean distance is positive otherwise negative.
            if first_user == second_user:
                tmp_dist = np.linalg.norm(first_row - second_row)
            else:
                tmp_dist = -np.linalg.norm(first_row - second_row)
            print(tmp_dist)
            batch_dist += tmp_dist
            
    return batch_dist

In [31]:
def custom_loss_keras(user_id, encodings):
    pairwise_diff = K.expand_dims(encodings, 0) - K.expand_dims(encodings, 1)
    pairwise_squared_distance = K.sum(K.square(pairwise_diff), axis=-1)
    pairwise_distance = K.sqrt(pairwise_squared_distance + K.epsilon())

#     user_id = K.squeeze(user_id, axis=1)  # remove the axis added by Keras
    pairwise_equal = K.equal(K.expand_dims(user_id, 0), K.expand_dims(user_id, 1))

    pos_neg = K.cast(pairwise_equal, K.floatx()) * 2 - 1
    return K.sum(pairwise_distance * pos_neg, axis=-1) / 2

encodings = np.random.rand(32, 10)
user_id = np.random.randint(10, size=32)

print(K.eval(custom_loss_keras(K.variable(user_id), K.variable(encodings))).sum())
print(custom_loss_numpy(pd.DataFrame(encodings), pd.Series(user_id)))

InternalError: Failed to create session.

In [17]:
import keras.backend as K
import numpy as np
import keras

a = np.array([1.0,0,1,0,1,1,1,1,0,0,0])
# a = a.astype(float)

In [25]:
b = K.eval(K.cast(a, dtype='float32'))

In [26]:
b

array([1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0.], dtype=float32)

In [31]:
keras.utils.to_categorical(a)

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [7]:
import numpy as np
length = 5
seq = np.array([i/float(length) for i in range(length)])
X = seq.reshape(len(seq), 1, 1)
X

array([[[0. ]],

       [[0.2]],

       [[0.4]],

       [[0.6]],

       [[0.8]]])

In [9]:
X = seq.reshape(1, length, 1)
X

array([[[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]])

In [10]:
y = seq.reshape(1, length)
y

array([[0. , 0.2, 0.4, 0.6, 0.8]])